#!/bin/bash

LOG_FILE=/tmp/ipApply.log
WORK_DIR=/root/rdbi-work

log() {
    echo "$1" >> $LOG_FILE
    printf "$1\n"
}

ipApply_start() {
    log "ipApply start"
    nohup $WORK_DIR/ipApply >> $LOG_FILE 2>&1 &
}

start() {
    log "Starting ipApply\n"
    ipApply_start
    log "done"
}

stop() {
    echo "Stopping ipApply work"
    if ps -A | grep -q "ipApply"; then
        pid=$(ps -A | grep "ipApply" | awk '{print $1}')
        kill "$pid"
        log "stop ipApply:$pid"
    else
        log "ipApply not exit"
    fi
    echo "done"
}

restart() {
    stop
    start
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart}"
        exit 1
esac

exit $?